### PR TITLE
Revert "Integerating api"

### PR DESCRIPTION
**Pull request by Muhammad-Sharjeel50**
Reverts Muhammad-Sharjeel50/bloggingwebsitemean#2

### CODE REVIEW

**Comment by UzairDanyal** [comment]
image
This one is not completed I guess

**Comment by UzairDanyal** [comment]
image
do not use href for routing in angular This must be done with  routrelink

**Comment by UzairDanyal** [comment]
image
this shouldn't call here 

if no nested routing is being used then only one router outlet can perform the required functionality

**Comment by UzairDanyal** [comment]
image
Try to never use any keyword for a data type

**Comment by UzairDanyal** [comment]
image
Will discuss  folder structure on Monday

**Comment by Muhammad-Sharjeel50** [comment]
NO Actually the latest data is on the AdditionalFeatures

**Pull request closed without merging**
